from building import *

cwd = GetCurrentDir()
group = []

# add the general drivers.
#src = Glob('*.c')

src = Split("""
boot.c
os.c
sbl_boot.c
""")

if GetDepend(['CONFIG_BOOT_SIGNATURE']):
    src.append('keys.c')

CPPPATH = [cwd,cwd + '/include']

group = DefineGroup('boot', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
      group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
