from building import *

# The set of source files associated with this SConscript file.
cwd = GetCurrentDir()

# add the common files.
src = []

CPPPATH = [cwd]

if GetDepend(['CONFIG_BOOT_SIGNATURE_TYPE_ROM']):
    if GetDepend(['SOC_LPC55S69_SERIES']):
    	src += ['./image_lpc55xx.c']
    if GetDepend(['SOC_IMXRTYYYY_SERIES']):
        src += ['./hab.c']
        src += ['./hab_rvt.c']
        src += ['./image_hab.c'] 

if GetDepend(['CONFIG_BOOT_SIGNATURE_TYPE_AES_CCM']):
	src += ['./image_ccm.c']

if GetDepend(['CONFIG_BOOT_ENCRYPTED_XIP']):
	src += ['./update_key_context.c']

group = DefineGroup('semifunc', src, depend = ['COMPONENT_MCUBOOT_SECURE'], CPPPATH = CPPPATH)

Return('group')
